### PR TITLE
Changed availability in Profile Modal

### PR DESCRIPTION
**Pull request by tsumori91**
### What this PR does (required):
- Changes the availability in Profile model

### Any issues with the current functionality (optional):
- Still not 100% everyone is on board with this layout so please take a look.

### CODE REVIEW

**Comment by c-s-ale** [comment]
I think we'd be better off adding an array with two elements: startTime, and endTime if we're going to have 4 time slots anyway. Seems like it would offer finer control for the user, and would achieve a similar goal to what we're looking for. 

It's also easy enough to work with!

**Comment by tsumori91** [comment]
> I think we'd be better off adding an array with two elements: startTime, and endTime if we're going to have 4 time slots anyway. Seems like it would offer finer control for the user, and would achieve a similar goal to what we're looking for.
> 
> It's also easy enough to work with!
> 
> EDIT:
> 
> On second thought, the way I'm suggesting does not cover the case of needing a dog sitter in the morning, and night, and not in the middle of the day!

Yeah it's a tradeoff, I think making start/endtimes isn't as user friendly/fluid as a few simple timeslots, but then it doesn't allow for fine tuning. Personally since this won't be actually used, I thought the timeslots would be a better choice since it will look nicer visually

**Comment by c-s-ale** [comment]
Thinking more about it, why not just do an array of 7 days, and then the 2-3 timeslots within each day?

**Comment by moffatethan** [comment]
My one comment I'll make on this as I want you all as a team to discuss a potential solution. Think of how this will be implemented on the front-end, will you use a third party library for the calendar functionality? How does that 3rd party library work. How will we determine their schedule? These are all things to consider, I think this is a good start on some discussion.

**Pull request merged**
